### ISSUE TITLE
How did you make greetings in webDemo? 

### ISSUE THREAD

**Issue by theotheo** [htaunay/remindmebot#1]
Hi! Could you please tell how you did this greetings? 
![screenshot_223](https://cloud.githubusercontent.com/assets/1499744/14821474/8fa2e9cc-0bd3-11e6-8050-1348efb5549e.jpg)

**Comment by htaunay** [comment]
Hi!

The greeting is automatically generated by the [Microsoft Bot Framework](https://dev.botframework.com/), more specifically by the Web Chat channel. Basically, after you have a working bot, you can configure it to be a [connector bot](https://github.com/htaunay/remindmebot/blob/master/botConnectorBot.js), allowing it to use MS's connector tool to easily integrate it with other platforms (e.g. Skype, Telegram).

You can test this behavior by just running the [text bot](https://github.com/htaunay/remindmebot/blob/master/textBot.js) version and noticing that no greeting is given.

Hope it helped!
